# Generated by Django 5.1.6 on 2025-03-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=8)),
                ('bio', models.TextField(blank=True, max_length=150)),
                ('profile_picture', models.ImageField(blank=True, upload_to='photos/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
