# Generated by Django 5.1.6 on 2025-03-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_followers_userprofile_following_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3ADefault_pfp.jpg&psig=AOvVaw3fhkfUk6VXN-Uc9y-dKrIW&ust=1743369946894000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCKDLpKSdsIwDFQAAAAAdAAAAABAE', upload_to='photos/'),
        ),
    ]
