# Generated by Django 5.1.6 on 2025-03-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='post_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
